[general]
host = "0.0.0.0"
port = 6432
connect_timeout = 500
ban_time = 60
admin_username = "admin_user"
admin_password = "admin_pass"

[pools.test_db]
pool_mode = "transaction"

[pools.test_db.users.0]
username = "postgres"
password = "postgres"
pool_size = 1

[pools.test_db.shards.0]
servers = [["0.0.0.0", 5432, "primary"]]
database = "postgres"
